In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
url = 'https://raw.githubusercontent.com/cibelerusso/Datasets/main/DadoseDecisoes.csv'
df = pd.read_csv(url, decimal='.')

In [35]:
df.head()

,ID,Idade,Gênero,Departamento,Salário,Horas_Trabalhadas,Produtividade,Satisfação,Tempo_Empresa,Cursos_Realizados,Home_Office
0,1,34,Masculino,RH,3848.89,36,84.89,94.33,0,4,Não
1,2,39,Feminino,Vendas,2536.32,48,107.84,98.62,4,9,Sim
2,3,39,Masculino,Marketing,7377.81,44,95.66,80.23,11,6,Sim
3,4,27,Feminino,Vendas,2536.32,40,88.89,94.63,8,1,Sim
4,5,41,Feminino,Vendas,2536.32,37,80.97,86.44,11,12,Não

(a) Inicialmente, classifique os funcion´arios em dois grupos (Produtividade bin: ”Alta”ou ”Baixa”):

• Alta produtividade: funcion´arios com produtividade acima da mediana;

• Baixa produtividade: funcion´arios com produtividade abaixo ou igual `a mediana.

In [36]:
median_prod = df['Produtividade'].median()
print(median_prod)

def classificar_produtividade(Produtividade):
    if Produtividade > median_prod:
        return "Alta"
    elif Produtividade < median_prod:
        return "Baixa"

df['Produtividade_bin'] = df['Produtividade'].apply(classificar_produtividade)

df.head()

87.04

,ID,Idade,Gênero,Departamento,Salário,Horas_Trabalhadas,Produtividade,Satisfação,Tempo_Empresa,Cursos_Realizados,Home_Office,Produtividade_bin
0,1,34,Masculino,RH,3848.89,36,84.89,94.33,0,4,Não,Baixa
1,2,39,Feminino,Vendas,2536.32,48,107.84,98.62,4,9,Sim,Alta
2,3,39,Masculino,Marketing,7377.81,44,95.66,80.23,11,6,Sim,Alta
3,4,27,Feminino,Vendas,2536.32,40,88.89,94.63,8,1,Sim,Alta
4,5,41,Feminino,Vendas,2536.32,37,80.97,86.44,11,12,Não,Baixa